### ISSUE TITLE
ApplicationRecord vs. ActiveRecord::Base in viikko1.md

### ISSUE THREAD

**Issue by JHamberg** [mluukkai/WebPalvelinohjelmointi2018#2]
In [viikko1.md](https://github.com/mluukkai/WebPalvelinohjelmointi2018/blob/f4a8a9e56c7888afcc56feb13ec1496204017a48/web/viikko1.md) we create a Brewery using `rails g scaffold brewery name:string year:integer` which then (according to material) generates:
```ruby
class Brewery < ApplicationRecord
end
```
but later in the document, we take another look at the file which has now become:
```ruby
class Brewery < ActiveRecord::Base
end
``` 
Why have we switched from ApplicationRecord to the class it inherits from?

**Comment by mluukkai** [comment]
Copypaste error. Now fixed. The correct class was _ActiveRecord::Base_ before Rails 5. It works still fine but better to use _ApplicationRecord_
